version: "3.8"
services:
  cashcard-app:
    image: cashcard-app:main
    container_name: cash-main
    networks:
      mynet:
        ipv4_address: 172.30.240.10
    ports:
      - "5000:5000"

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.240.0/20
